// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Analyzes website content for potential security threats.
 *
 * - analyzeWebsiteContent - A function that analyzes website content for security threats.
 * - AnalyzeWebsiteContentInput - The input type for the analyzeWebsiteContent function.
 * - AnalyzeWebsiteContentOutput - The return type for the analyzeWebsiteContent function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import {getReputation} from '@/services/threat-intelligence';

const AnalyzeWebsiteContentInputSchema = z.object({
  url: z.string().describe('The URL of the website to analyze.'),
  content: z.string().describe('The content of the website to analyze.'),
});
export type AnalyzeWebsiteContentInput = z.infer<typeof AnalyzeWebsiteContentInputSchema>;

const AnalyzeWebsiteContentOutputSchema = z.object({
  threatLevel: z
    .string()
    .describe(
      'The threat level of the website content, can be one of: high, medium, low, safe.'
    ),
  threatDescription: z.string().describe('A description of the detected threats.'),
  reputationScore: z.number().describe('The reputation score of the domain (0-100).'),
  reputationDescription: z
    .string()
    .describe('A description of why the domain has this reputation'),
  reputationCategory: z.enum(['Super Safe', 'Safe', 'Medium', 'Low', 'Critical', 'Unknown'])
    .describe('The safety category of the domain based on its reputation.'),
});
export type AnalyzeWebsiteContentOutput = z.infer<typeof AnalyzeWebsiteContentOutputSchema>;

export async function analyzeWebsiteContent(
  input: AnalyzeWebsiteContentInput
): Promise<AnalyzeWebsiteContentOutput> {
  return analyzeWebsiteContentFlow(input);
}

const analyzeWebsiteContentPrompt = ai.definePrompt({
  name: 'analyzeWebsiteContentPrompt',
  input: {
    schema: z.object({
      url: z.string().describe('The URL of the website to analyze.'),
      content: z.string().describe('The content of the website to analyze.'),
    }),
  },
  output: {
    schema: z.object({
      threatLevel: z
        .string()
        .describe(
          'The threat level of the website content, can be one of: high, medium, low, safe.'
        ),
      threatDescription: z.string().describe('A description of the detected threats.'),
    }),
  },
  prompt: `You are a security expert analyzing website content for potential threats like phishing and malware.

Analyze the following website content and determine the threat level (high, medium, low, safe) and provide a description of the detected threats.

URL: {{{url}}}
Content: {{{content}}}
\nThreat Level:`,
});

const analyzeWebsiteContentFlow = ai.defineFlow<
  typeof AnalyzeWebsiteContentInputSchema,
  typeof AnalyzeWebsiteContentOutputSchema
>(
  {
    name: 'analyzeWebsiteContentFlow',
    inputSchema: AnalyzeWebsiteContentInputSchema,
    outputSchema: AnalyzeWebsiteContentOutputSchema,
  },
  async input => {
    const {output: promptOutput} = await analyzeWebsiteContentPrompt(input);

    const reputation = await getReputation(input.url);

    return {
      threatLevel: promptOutput!.threatLevel,
      threatDescription: promptOutput!.threatDescription,
      reputationScore: reputation.reputationScore,
      reputationDescription: reputation.reputationDescription,
      reputationCategory: reputation.category,
    };
  }
);